var searchData=
[
  ['backoff',['Backoff',['../classhoney_1_1lockfree_1_1_backoff.html',1,'honey::lockfree']]],
  ['backsub',['BackSub',['../classhoney_1_1_back_sub.html',1,'honey']]],
  ['beta_5f',['Beta_',['../classhoney_1_1_beta__.html',1,'honey']]],
  ['betainc',['BetaInc',['../classhoney_1_1_beta_inc.html',1,'honey']]],
  ['binomial_5f',['Binomial_',['../classhoney_1_1_binomial__.html',1,'honey']]],
  ['binomialneg_5f',['BinomialNeg_',['../classhoney_1_1_binomial_neg__.html',1,'honey']]],
  ['bisect',['Bisect',['../classhoney_1_1_bisect.html',1,'honey']]],
  ['bisectn',['BisectN',['../classhoney_1_1_bisect_n.html',1,'honey']]],
  ['bitopcommon',['BitOpCommon',['../structhoney_1_1_bit_op_common.html',1,'honey']]],
  ['bitopendian',['BitOpEndian',['../structhoney_1_1_bit_op_endian.html',1,'honey']]],
  ['bitopendian_3c_20static_5fcast_3c_20int_20_3e_28endian_3a_3abig_29_3e',['BitOpEndian&lt; static_cast&lt; int &gt;(Endian::big)&gt;',['../structhoney_1_1_bit_op_endian_3_01static__cast_3_01int_01_4_07_endian_1_1big_08_4.html',1,'honey']]],
  ['bitopendian_3c_20static_5fcast_3c_20int_20_3e_28endian_3a_3alittle_29_3e',['BitOpEndian&lt; static_cast&lt; int &gt;(Endian::little)&gt;',['../structhoney_1_1_bit_op_endian_3_01static__cast_3_01int_01_4_07_endian_1_1little_08_4.html',1,'honey']]],
  ['bitset_5f',['BitSet_',['../classhoney_1_1_bit_set__.html',1,'honey']]],
  ['bitset_5f_3c_20block_2c_20alloc_20_3e',['BitSet_&lt; Block, Alloc &gt;',['../classhoney_1_1_bit_set__.html',1,'honey']]],
  ['block',['Block',['../classhoney_1_1matrix_1_1_block.html',1,'honey::matrix']]],
  ['blockheader',['BlockHeader',['../structhoney_1_1_mem_pool_1_1_bucket_1_1_block_header.html',1,'honey::MemPool::Bucket']]],
  ['blockheader',['BlockHeader',['../structhoney_1_1_mem_pool_1_1_heap_1_1_block_header.html',1,'honey::MemPool::Heap']]],
  ['blocktraits',['BlockTraits',['../structhoney_1_1matrix_1_1priv_1_1_block_traits.html',1,'honey::matrix::priv']]],
  ['blocktraits_3c_20matrixp_2c_20rows_2c_20cols_20_3e',['BlockTraits&lt; MatrixP, Rows, Cols &gt;',['../structhoney_1_1matrix_1_1priv_1_1_block_traits.html',1,'honey::matrix::priv']]],
  ['blocktraits_3c_20vec_2c_201_2c_201_20_3e',['BlockTraits&lt; Vec, 1, 1 &gt;',['../structhoney_1_1matrix_1_1priv_1_1_block_traits.html',1,'honey::matrix::priv']]],
  ['blocktraits_3c_20vec_2c_201_2c_20cols_20_3e',['BlockTraits&lt; Vec, 1, Cols &gt;',['../structhoney_1_1matrix_1_1priv_1_1_block_traits.html',1,'honey::matrix::priv']]],
  ['blocktraits_3c_20vec_2c_20rows_2c_201_20_3e',['BlockTraits&lt; Vec, Rows, 1 &gt;',['../structhoney_1_1matrix_1_1priv_1_1_block_traits.html',1,'honey::matrix::priv']]],
  ['bloomfilter',['BloomFilter',['../classhoney_1_1_bloom_filter.html',1,'honey']]],
  ['bootstrap',['Bootstrap',['../classhoney_1_1_bootstrap.html',1,'honey']]],
  ['broken',['Broken',['../structhoney_1_1future_1_1_broken.html',1,'honey::future']]],
  ['buffer',['Buffer',['../classhoney_1_1_buffer.html',1,'honey']]],
  ['buffersink',['BufferSink',['../structhoney_1_1log_1_1_buffer_sink.html',1,'honey::log']]],
  ['builder',['Builder',['../classhoney_1_1matrix_1_1_builder.html',1,'honey::matrix']]],
  ['bytearray',['ByteArray',['../structhoney_1_1_byte_array.html',1,'honey']]],
  ['bytearray_3c_2032_20_3e',['ByteArray&lt; 32 &gt;',['../structhoney_1_1_byte_array.html',1,'honey']]],
  ['bytes',['Bytes',['../classhoney_1_1_bytes.html',1,'honey']]],
  ['bytestream',['ByteStream',['../classhoney_1_1_byte_stream.html',1,'honey']]],
  ['bytestreambuf',['ByteStreamBuf',['../classhoney_1_1_byte_stream_buf.html',1,'honey']]]
];
