var searchData=
[
  ['scopeguard_5f',['ScopeGuard_',['../classhoney_1_1_scope_guard__.html',1,'honey']]],
  ['segment',['Segment',['../structhoney_1_1vec_1_1priv_1_1_segment.html',1,'honey::vec::priv']]],
  ['setalign',['setAlign',['../structhoney_1_1matrix_1_1_option_1_1set_align.html',1,'honey::matrix::Option']]],
  ['sharedfuture',['SharedFuture',['../classhoney_1_1_shared_future.html',1,'honey']]],
  ['sharedlock',['SharedLock',['../classhoney_1_1_shared_lock.html',1,'honey']]],
  ['sharedmutex',['SharedMutex',['../classhoney_1_1_shared_mutex.html',1,'honey']]],
  ['sharedobj',['SharedObj',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20deptask_20_3e',['SharedObj&lt; DepTask &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20exception_20_3e',['SharedObj&lt; Exception &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20listener_20_3e',['SharedObj&lt; Listener &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20module_20_3e',['SharedObj&lt; Module &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20object_20_3e',['SharedObj&lt; Object &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20periodictask_20_3e',['SharedObj&lt; PeriodicTask &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20pool_20_3e',['SharedObj&lt; Pool &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20sink_20_3e',['SharedObj&lt; Sink &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedobj_3c_20state_20_3e',['SharedObj&lt; State &gt;',['../classhoney_1_1_shared_obj.html',1,'honey']]],
  ['sharedptr',['SharedPtr',['../classhoney_1_1_shared_ptr.html',1,'honey']]],
  ['sharedptr_3c_20periodictask_20_3e',['SharedPtr&lt; PeriodicTask &gt;',['../classhoney_1_1_shared_ptr.html',1,'honey']]],
  ['sharedptr_3c_20state_20_3e',['SharedPtr&lt; State &gt;',['../classhoney_1_1_shared_ptr.html',1,'honey']]],
  ['sharedptr_3c_20thread_3a_3apool_20_3e',['SharedPtr&lt; thread::Pool &gt;',['../classhoney_1_1_shared_ptr.html',1,'honey']]],
  ['signal',['Signal',['../structhoney_1_1_signal.html',1,'honey']]],
  ['simplexnoise',['SimplexNoise',['../classhoney_1_1_simplex_noise.html',1,'honey']]],
  ['simplexnoisecommon',['SimplexNoiseCommon',['../classhoney_1_1_simplex_noise_common.html',1,'honey']]],
  ['simplexnoisecommon_3c_20simplexnoise_3c_20dim_2c_20real_20_3e_2c_20dim_2c_20real_20_3e',['SimplexNoiseCommon&lt; SimplexNoise&lt; Dim, Real &gt;, Dim, Real &gt;',['../classhoney_1_1_simplex_noise_common.html',1,'honey']]],
  ['sink',['Sink',['../structhoney_1_1log_1_1_sink.html',1,'honey::log']]],
  ['sintable',['SinTable',['../classhoney_1_1_sin_table.html',1,'honey']]],
  ['size_5f',['size_',['../structhoney_1_1_mt_map_common_1_1size__.html',1,'honey::MtMapCommon']]],
  ['size_5f',['size_',['../structhoney_1_1variant_1_1size__.html',1,'honey::variant']]],
  ['sizer',['sizeR',['../structhoney_1_1_mt_map_common_1_1priv_1_1size_r.html',1,'honey::MtMapCommon::priv']]],
  ['sizer',['sizeR',['../structhoney_1_1_mt_map_common_1_1priv_3_01true_00_01___01_4_1_1size_r.html',1,'honey::MtMapCommon::priv&lt; true, _ &gt;']]],
  ['slotbase',['SlotBase',['../classhoney_1_1_slot_base.html',1,'honey']]],
  ['smallallocator',['SmallAllocator',['../classhoney_1_1_small_allocator.html',1,'honey']]],
  ['socket',['Socket',['../classhoney_1_1net_1_1_socket.html',1,'honey::net']]],
  ['source',['Source',['../structhoney_1_1_exception_1_1_source.html',1,'honey::Exception']]],
  ['spinlock',['SpinLock',['../classhoney_1_1_spin_lock.html',1,'honey']]],
  ['spscdeque',['SpscDeque',['../classhoney_1_1lockfree_1_1_spsc_deque.html',1,'honey::lockfree']]],
  ['stack',['Stack',['../classhoney_1_1lockfree_1_1_stack.html',1,'honey::lockfree']]],
  ['state',['State',['../structhoney_1_1_chacha_1_1_state.html',1,'honey::Chacha']]],
  ['stats',['Stats',['../structhoney_1_1_student_t___1_1_stats.html',1,'honey::StudentT_']]],
  ['std',['Std',['../structhoney_1_1exception_1_1_std.html',1,'honey::exception']]],
  ['storage',['Storage',['../structhoney_1_1matrix_1_1priv_1_1_storage.html',1,'honey::matrix::priv']]],
  ['storage',['Storage',['../structhoney_1_1vec_1_1priv_1_1_storage.html',1,'honey::vec::priv']]],
  ['storageauto',['StorageAuto',['../classhoney_1_1matrix_1_1priv_1_1_storage_auto.html',1,'honey::matrix::priv']]],
  ['storageautoarray',['StorageAutoArray',['../structhoney_1_1matrix_1_1priv_1_1_storage_auto_array.html',1,'honey::matrix::priv']]],
  ['storageautoarray_3c_20real_2c_20honey_3a_3amatrix_3a_3apriv_3a_3astoragedense_3a_3as_5fsize_2c_20honey_3a_3amatrix_3a_3aoption_3a_3agetalign_3c_20honey_3a_3amatrix_3a_3apriv_3a_3astoragedense_3a_3aoptions_20_3e_3a_3avalue_20_3e',['StorageAutoArray&lt; Real, honey::matrix::priv::StorageDense::s_size, honey::matrix::Option::getAlign&lt; honey::matrix::priv::StorageDense::options &gt;::value &gt;',['../structhoney_1_1matrix_1_1priv_1_1_storage_auto_array.html',1,'honey::matrix::priv']]],
  ['storageautoarray_3c_20real_2c_20size_2c_2016_20_3e',['StorageAutoArray&lt; Real, Size, 16 &gt;',['../structhoney_1_1matrix_1_1priv_1_1_storage_auto_array_3_01_real_00_01_size_00_0116_01_4.html',1,'honey::matrix::priv']]],
  ['storageblock',['StorageBlock',['../classhoney_1_1matrix_1_1priv_1_1_storage_block.html',1,'honey::matrix::priv']]],
  ['storagedense',['StorageDense',['../structhoney_1_1matrix_1_1priv_1_1_storage_dense.html',1,'honey::matrix::priv']]],
  ['storagedynamic',['StorageDynamic',['../classhoney_1_1matrix_1_1priv_1_1_storage_dynamic.html',1,'honey::matrix::priv']]],
  ['storagefields',['StorageFields',['../classhoney_1_1vec_1_1priv_1_1_storage_fields.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin',['StorageFieldsMixin',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20matrix_3a_3apriv_3a_3atraits_3c_20subclass_20_3e_3a_3areal_2c_20matrix_3a_3apriv_3a_3atraits_3c_20subclass_20_3e_3a_3adim_2c_20matrix_3a_3aoption_3a_3agetalign_3c_20matrix_3a_3apriv_3a_3atraits_3c_20subclass_20_3e_3a_3aoptions_20_3e_3a_3avalue_20_3e',['StorageFieldsMixin&lt; matrix::priv::Traits&lt; Subclass &gt;::Real, matrix::priv::Traits&lt; Subclass &gt;::dim, matrix::Option::getAlign&lt; matrix::priv::Traits&lt; Subclass &gt;::options &gt;::value &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20real_2c_201_2c_20align_20_3e',['StorageFieldsMixin&lt; Real, 1, Align &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin_3_01_real_00_011_00_01_align_01_4.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20real_2c_202_2c_20align_20_3e',['StorageFieldsMixin&lt; Real, 2, Align &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin_3_01_real_00_012_00_01_align_01_4.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20real_2c_203_2c_20align_20_3e',['StorageFieldsMixin&lt; Real, 3, Align &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin_3_01_real_00_013_00_01_align_01_4.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20real_2c_204_2c_2016_20_3e',['StorageFieldsMixin&lt; Real, 4, 16 &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin_3_01_real_00_014_00_0116_01_4.html',1,'honey::vec::priv']]],
  ['storagefieldsmixin_3c_20real_2c_204_2c_20align_20_3e',['StorageFieldsMixin&lt; Real, 4, Align &gt;',['../structhoney_1_1vec_1_1priv_1_1_storage_fields_mixin_3_01_real_00_014_00_01_align_01_4.html',1,'honey::vec::priv']]],
  ['streambuf_5f',['StreamBuf_',['../classhoney_1_1net_1_1_stream_buf__.html',1,'honey::net']]],
  ['streamsink',['StreamSink',['../structhoney_1_1log_1_1_stream_sink.html',1,'honey::log']]],
  ['string',['String',['../classhoney_1_1_string.html',1,'honey']]],
  ['studentt_5f',['StudentT_',['../classhoney_1_1_student_t__.html',1,'honey']]],
  ['sub',['sub',['../structhoney_1_1_ratio_1_1sub.html',1,'honey::Ratio']]],
  ['sval',['sval',['../structhoney_1_1hash_1_1sval.html',1,'honey::hash']]],
  ['svd',['Svd',['../classhoney_1_1_svd.html',1,'honey']]],
  ['swaptype',['SwapType',['../structhoney_1_1atomic_1_1_swap_type.html',1,'honey::atomic']]],
  ['swaptype_3c_20t_20_2a_20_3e',['SwapType&lt; T * &gt;',['../structhoney_1_1atomic_1_1_swap_type.html',1,'honey::atomic']]],
  ['systemclock',['SystemClock',['../structhoney_1_1_system_clock.html',1,'honey']]]
];
